CHATS_ESTATE = ['alania_forlife',
                'olxalanya',
                'stambul_Antalia_Alania/40',
                'billboard_alanya_realestate',
                'alania_baraxlanet',
                'alaniyalife',
                'mahmutlarrussia',
                'mahmutlarru',
                'kupiprodaidarom',
                'alanyamahmutlargazipasa',
                'alanyalife4you',
                'alanya_bestchat',
                'alanya_2022',
                'AlanyaVse',
                'mahmutlarru_chat',
                'alanyaru',
                'globe_alaniya_chat',
                'turkey_public/17344',
                'alanya_chat_2',
                'Vmeste_Alanya',
                'alanyachat_baraholka',
                'alanya5',
                'chatalanya_turkey',
                'alanya_top',
                'alanya_profi',
                'globe_nedvizhka_alaniya',
                'rabotavturkish',
                'Alanyachat_turkey_mahmutlar_oba'
                ]

KEY_ESTATE = ['покуп',
              'купит',
              'купил',
              'купл',
              'аренду',
              'арендую',
              'арендуем',
              'сним',
              'приобре'
              ]

WHITE_ESTATE = ['квартир',
                'студи',
                'вилл',
                'апартамент',
                'жиль',
                'дом',
                'дуплекс',
                'дюплекс'
                ]

BLACK_ESTATE = ['добро пожаловать в наш чат',
                'ознакомься с правилами',
                'ОПРОС-ПРОВЕРКА НОВОГО УЧАСТНИКА',
                ]
