CHATS_MONEY = ['+jzWUJ4kYorQ4YWI6',
               'AlanyaVse',
               'GlavTurkey',
               'Turkey_Money_Exchange',
               'Vmeste_Alanya',
               'alania_forlife',
               'alaniya_chat_kg',
               'alaniyalife',
               'alanya_2022',
               'alanya_bestchat',
               'alanya_chat_2',
               'alanya_fm',
               'alanya_forum',
               'alanya_novostialanya5',
               'alanya_profi',
               'alanya_top',
               'alanyachat01',
               'alanyachat_baraholka',
               'alanyachat_cho',
               'alanyachat_cho',
               'alanyaforu',
               'alanyal',
               'alanyalife4you',
               'alanyamahmutlargazipasa',
               'alanyaru',
               'alanyayes',
               'antalya_chat_emigrantus',
               'chatalanya_turkey',
               'exchangerMA',
               'financeAlania',
               'globe_alaniya_chat',
               'globe_mahmutlar',
               'mahmutlar_online',
               'mahmutlarru',
               'mahmutlarru_chat',
               'mahmutlarrussia',
               'mamochkanamore',
               'obmen_valut_Turkey24',
               'russkayalanya',
               'svoi_alania_sale',
               'teleport_exchange',
               'turkchanger',
               'turkey_public/1',
               'turkey_public/17338',
               'turkey_public/20273',
               'test_Alexandra_Exchange'
               ]

KEY_MONEY = ['курс',
             'какой',
             'обмен',
             'обменник',
             'поменя',
             'менят',
             'менял',
             'меняю',
             'меняе',
             'покуп',
             'хочу поменять',
             'хочу разменять',
             'кто поменяет',
             'кто разменяет',
             'подскаж',
             'подсказ',
             'купить лиры',
             'куплю лиры',
             'перевод',
             'перевес',
             'сбербанк',
             'тиньков',
             'российск'
             ]

WHITE_MONEY = ['рубл',
               'гривн',
               'лир',
               'доллар',
               'бакс',
               'евр',
               'валют',
               'деньг',
               'наличн',
               'курс',
               'обменник',
               'обмен',
               'меняе',
               'нужен',
               'нужн',
               'банк',
               'менят',
               'сбербанк',
               'тиньков'
               ]


BLACK_MONEY = ['добро пожаловать в наш чат',
               'ознакомься с правилами',
               'ОПРОС-ПРОВЕРКА НОВОГО УЧАСТНИКА',
               'ОПЕРАЦИОННАЯ КАССА',
               'канал',
               'в курсе',
               'курсы',
               'витамин',
               'конкурс',
               'экскурс',
               'ракурс',
               'госкурс',
               'присяжн',
               'переводчик',
               'нотари',
               'муниципал',
               'школ',
               'заняти',
               'сеанс',
               'метод',
               'учени',
               'учебн',
               'обучен',
               'язык',
               'трейдинг',
               'преподава',
               'водительск',
               'удостоверени',
               'автомобил',
               'зараб',
               'капуста',
               'арбитраж',
               'нович',
               'партнер',
               'команд',
               'подработк',
               'подроботк',
               'оплат',
               'стоимост',
               'гаранти',
               'безопасност',
               'связк',
               'крипт',
               'крuпт',
               'ⲕpипт',
               'crypt',
               'usdt',
               'Swift',
               'p2p',
               'binance',
               'бесплатн',
               'нейро',
               'поможем',
               'возвра',
               'офис',
               'оՓиc',
               'мира',
               'приложени',
               'корон',
               'почт',
               'айфон',
               'iphone',
               'смартфон',
               'All Inclusive',
               'скидк',
               'налог',
               'площадь',
               'аренд',
               'собственник',
               'вменя',
               'примен',
               'замен',
               'подмен'
               'оформлен',
               'дистилир',
               'кухн',
               'санузл',
               'гостиная',
               'дуплекс',
               'дюплекс',
               'комплекс',
               'автовокзал',
               'остановк',
               'документ'
               ]
