CHATS = ['+jzWUJ4kYorQ4YWI6',
         'AlanyaVse',
         'Vmeste_Alanya',
         'alania_forlife',
         'alaniya_chat_kg',
         'alaniyalife',
         'alanya5',
         'alanya_2022',
         'alanya_bestchat',
         'alanya_chat_2',
         'alanya_forum',
         'alanya_profi',
         'alanya_top',
         'alanyachat_baraholka',
         'alanyachat_cho',
         'alanyalife4you',
         'alanyamahmutlargazipasa',
         'alanyaru',
         'chatalanya_turkey',
         'globe_alaniya_chat',
         'mahmutlar_online',
         'mahmutlarru',
         'mahmutlarru_chat',
         'mahmutlarrussia',
         'mamochkanamore',
         'test_Alexandra_Exchange',
         'turkey_public/1',
         'turkey_public/17338',
         'turkey_public/20273'
         ]

KEY_WORDS = ['обмен',
             'поменя',
             'менят',
             'перевод',
             'курс',
             'наличн',
             'деньг',
             'рубл',
             'валют',
             'купить лиры',
             'куплю лиры',
             'на лиры',
             'на турецкие лиры'
             ]

BLACK_LIST = ['добро пожаловать в наш чат',
              'ознакомься с правилами',
              'канал',
              'в курсе',
              'курсы',
              'конкурс',
              'экскурс',
              'ракурс',
              'присяжн',
              'переводчик',
              'устный перевод',
              'нотари',
              'школ',
              'заняти',
              'сеанс',
              'метод',
              'учени',
              'учебн',
              'языков',
              'трейдинг',
              'преподава',
              'водительск',
              'удостоверени',
              'зараб',
              'капуста',
              'арбитраж',
              'нович',
              'партнер',
              'крипт',
              'крuпт',
              'crypt',
              'usdt',
              'Swift',
              'binance',
              'бесплатн',
              'нейро',
              'поможем',
              'возвра',
              'офис',
              'мира',
              'обучен',
              'приложени',
              'корон',
              'почт',
              'айфон',
              'iphone',
              'смартфон',
              'All Inclusive',
              'скидк',
              'диагноз',
              'врач',
              'сеанс',
              'минивен',
              'трансфер',
              'бензин',
              'литр',
              'заправк',
              'нефт',
              'glo',
              'iqos',
              'гло',
              'айкос',
              'кидает',
              'замки',
              'электрик',
              'сантехник'
              ]
