CHATS = ['+jzWUJ4kYorQ4YWI6',
         'AlanyaVse',
         'Vmeste_Alanya',
         'alania_forlife',
         'alaniya_chat_kg',
         'alaniyalife',
         'alanya5',
         'alanya_2022',
         'alanya_bestchat',
         'alanya_chat_2',
         'alanya_forum',
         'alanya_profi',
         'alanya_top',
         'alanyachat_baraholka',
         'alanyachat_cho',
         'alanyalife4you',
         'alanyamahmutlargazipasa',
         'alanyaru',
         'chatalanya_turkey',
         'globe_alaniya_chat',
         'mahmutlar_online',
         'mahmutlarru',
         'mahmutlarru_chat',
         'mahmutlarrussia',
         'mamochkanamore',
         'test_Alexandra_Exchange',
         'turkey_public/1',
         'turkey_public/17338',
         'turkey_public/20273'
         ]

KEY_WORDS = ['курс',
             'обмен',
             'поменя',
             'менят',
             'менял',
             'меняю',
             'меняе',
             'покуп',
             'купит',
             'купил',
             'купл',
             'перевод',
             'перевес',
             ]

WHITE_LIST = ['рубл',
              'гривн',
              'лир',
              'доллар',
              'бакс',
              'евр',
              'валют',
              'деньг',
              'наличн',
              'курс'
              ]


BLACK_LIST = ['добро пожаловать в наш чат',
              'ознакомься с правилами',
              'ОПРОС-ПРОВЕРКА НОВОГО УЧАСТНИКА',
              'канал',
              'в курсе',
              'курсы',
              'витамин',
              'конкурс',
              'экскурс',
              'ракурс',
              'госкурс',
              'присяжн',
              'переводчик',
              'устный перевод',
              'нотари',
              'муниципал',
              'школ',
              'заняти',
              'сеанс',
              'метод',
              'учени',
              'учебн',
              'обучен',
              'язык',
              'трейдинг',
              'преподава',
              'водительск',
              'удостоверени',
              'автомобил',
              'зараб',
              'капуста',
              'арбитраж',
              'нович',
              'партнер',
              'крипт',
              'крuпт',
              'crypt',
              'usdt',
              'Swift',
              'binance',
              'бесплатн',
              'нейро',
              'поможем',
              'возвра',
              'офис',
              'мира',
              'приложени',
              'корон',
              'почт',
              'айфон',
              'iphone',
              'смартфон',
              'All Inclusive',
              'скидк',
              'налог',
              'площадь',
              'аренд',
              'собственник',
              'вменя',
              'примен',
              'замен',
              'подмен'
              'оформлен',
              'дистилир'
              ]
