CHATS = ['+jzWUJ4kYorQ4YWI6',
         'AlanyaVse',
         'Vmeste_Alanya',
         'alania_forlife',
         'alaniya_chat_kg',
         'alaniyalife',
         'alanya5',
         'alanya_2022',
         'alanya_bestchat',
         'alanya_chat_2',
         'alanya_forum',
         'alanya_profi',
         'alanya_top',
         'alanyachat_baraholka',
         'alanyachat_cho',
         'alanyalife4you',
         'alanyamahmutlargazipasa',
         'alanyaru',
         'chatalanya_turkey',
         'globe_alaniya_chat',
         'mahmutlar_online',
         'mahmutlarru',
         'mahmutlarru_chat',
         'mahmutlarrussia',
         'mamochkanamore',
         'test_Alexandra_Exchange',
         'turkey_public/1',
         'turkey_public/17338',
         'turkey_public/20273'
         ]

KEY_WORDS = ['обмен', 'помен', 'перевод', 'курс', 'наличн', 'деньг', 'рубл', 'валют']

BLACK_LIST = ['добро пожаловать в наш чат',
              'ознакомься с правилами',
              'заходите на канал',
              'в курсе',
              'конкурс',
              'присяжный',
              'переводчик',
              'устный перевод',
              'нотари',
              'заработ',
              'капуста',
              'арбитраж',
              'крипто'
              ]
